docs: :memo: #EIRUNE-693 documentação Eitri-App Start
Calindra/eitri-docs pull request #25
Opened 2024-10-09 19:31 UTC by lucassdr

#EIRUNE-693

2024-10-11 13:26 UTC, djmacloud requested changes

2024-10-11 13:26 UTC, djmacloud commented on en/docs/quick-guides/eitri-app-start.md
> +# Eitri-App Start
Seria melhor um título mais voltado para a funcionalidade da qual esse recurso trata, como por exemplo "Running multiple Eitri-apps" ou "Developing multiple Eitri-apps"

2024-10-11 13:26 UTC, djmacloud commented on en/docs/quick-guides/eitri-app-start.md
> +    - **focus**: Defines if the Eitri-App will be opened in the foreground;
Defines wich the Eitri-App will be opened in the foreground;

2024-10-11 13:26 UTC, djmacloud commented on en/docs/quick-guides/eitri-app-start.md
> +    - **focus**: Defines if the Eitri-App will be opened in the foreground;
Isso imaginando que possa ser apenas 1

2024-10-11 13:26 UTC, djmacloud commented on en/docs/quick-guides/eitri-app-start.md
> +    - **shared**: Defines if the Eitri-App is shared between other Eitri-Apps.
Defines wich Eitri-Apps are shared between other Eitri-Apps.

2024-10-11 13:26 UTC, djmacloud commented on en/docs/quick-guides/eitri-app-start.md
> +    - **shared**: Defines if the Eitri-App is shared between other Eitri-Apps.
Isso imaginando que podem ser mais de um

2024-10-11 13:26 UTC, djmacloud commented on en/docs/quick-guides/eitri-app-start.md
> +    - **focus**: Defines if the Eitri-App will be opened in the foreground;
Seria bom ter um exemplo de como fornecer o dado. É String?

2024-10-11 13:26 UTC, djmacloud commented on en/docs/quick-guides/eitri-app-start.md
> +    - **shared**: Defines if the Eitri-App is shared between other Eitri-Apps.
Seria bom fornecer um exemplo de como seria o dado. É String? Se são múltiplos, separa como? É Array?

2024-10-11 13:26 UTC, djmacloud commented on pt/docs/tutoriais/eitri-app-start.md
> +# Eitri-App Start
Mesmo ajuste do inglês

2024-10-11 13:26 UTC, djmacloud commented on pt/docs/tutoriais/eitri-app-start.md
> +    - **focus**: Define se o Eitri-App será aberto em primeiro plano;
mesmo ajuste do inglês

2024-10-11 13:26 UTC, djmacloud commented on pt/docs/tutoriais/eitri-app-start.md
> +    - **shared**: Define se o Eitri-App é compartilhado entre outros Eitri-Apps.
mesmo ajuste do inglês

2024-10-11 13:26 UTC, djmacloud commented on en/docs/quick-guides/eitri-app-start.md
> +// further information hidden
O que seria isso?

2024-10-11 13:26 UTC, djmacloud commented on pt/docs/tutoriais/eitri-app-start.md
> +// demais informações ocultas
mesmo ajuste do inglês

2024-10-11 13:26 UTC, djmacloud commented on en/docs/quick-guides/eitri-app-start.md
> +application-id: 'bd9b96af-ac33-492e-876c-6755b3aefaef'
Seria importante a informação de onde obter esse dado

2024-10-11 13:26 UTC, djmacloud commented on pt/docs/tutoriais/eitri-app-start.md
> +application-id: 'bd9b96af-ac33-492e-876c-6755b3aefaef'
mesmo ajuste do inglês

2024-10-11 13:26 UTC, djmacloud commented on en/docs/quick-guides/.pages
> +    - multiple-shared.md
É possível sinalizar no menu os itens "novos" com aquele íconezinho. Não me lembro como é feito, mas se não me engano é uma tag na própria página para a qual o menu aponta. Seria bacana atualizar esse ícone e tirar dos antigos e colocar nos novos que foram recentemente incluídos.

2024-10-11 13:26 UTC, djmacloud commented on pt/docs/tutoriais/.pages
> +    - multiple-shared.md
mesmo ajuste do inglês

2024-10-11 14:02 UTC, lucassdr commented on en/docs/quick-guides/eitri-app-start.md
> +    - **focus**: Defines if the Eitri-App will be opened in the foreground;
@djmacloud no caso o exemplo abaixo já exemplifica se é string, etc.

2024-10-11 14:06 UTC, lucassdr commented on en/docs/quick-guides/eitri-app-start.md
> +// further information hidden
É por causa que outros logs são exibidos, inclusive o QrCode.
Com isso não há necessidade de mostrar.
Até ficaria ruim colocar o QrCode na documentação.

2024-10-15 11:15 UTC, djmacloud approved these changes
Última sugestão, juro...rsrs

2024-10-15 11:15 UTC, djmacloud commented on en/docs/quick-guides/eitri-app-start.md
> +    - **shared**: Defines if the Eitri-App is shared between other Eitri-Apps.
Foi mal, eu havia comentado errado aqui....acho que o ideal seria:

    - **focus**: Defines which Eitri-App will be opened in the foreground;
    - **shared**: Defines if the Eitri-App is shared between other Eitri-Apps.

2024-10-17 17:44 UTC, merged