chore: add doc for i18n
Calindra/eitri-docs pull request #31
Opened 2024-11-28 18:48 UTC by gbfonseca

2024-11-28 18:52 UTC, lucassdr approved these changes

2024-11-29 13:06 UTC, djmacloud commented on en/docs/quick-guides/i18n.md
> +Internationalization, or i18n (an abbreviation based on the number of letters between the initial "i" and the final "n"), is the process of designing and developing software, websites, or systems so
Não vale a pena termos linkado em algum lugar aqui um endereço de referência que explique mais sobre a internacionalização?

2024-11-29 13:28 UTC, gbfonseca commented on en/docs/quick-guides/i18n.md
> +Internationalization, or i18n (an abbreviation based on the number of letters between the initial "i" and the final "n"), is the process of designing and developing software, websites, or systems so
Vou buscar uma referência boa e adicionar

2024-11-29 15:44 UTC, djmacloud approved these changes

2024-11-29 15:45 UTC, djmacloud requested changes

2024-11-29 15:45 UTC, djmacloud commented on en/docs/quick-guides/i18n.md
> +[Internationalization](https://learn.microsoft.com/pt-br/windows/win32/intl/understanding-internationalization){:target="_blank"}, or i18n (an abbreviation based on the number of letters between the
Aqui tá linkado pro conteúdo em pt-br...vale a pena ser o conteúdo em inglês

2024-12-02 18:38 UTC, djmacloud approved these changes

2024-12-02 18:58 UTC, merged